name: Azure Sentinel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cloud set --name ${{ secrets.AZURE_CLOUD }}
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run deployment script
      run: pwsh ./Sentinel/AZ_Sentinel_Deploy.ps1

    - name: Post Checkout repository
      run: |
        git config --global user.email "donotreply@microsoft.com"
        git config --global user.name "Sentinel"
        git add .
        git commit -m "Post deployment updates"
        git push origin main

    - name: Post Azure Login
      run: az account clear

    - name: Complete job
      run: echo "Deployment complete"
