name: Deploy Azure Sentinel Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        inlineScript: az cloud set --name ${{ secrets.CLOUD_ENV }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run deployment script
      run: |
        pwsh ./.github/workflows/azure-sentinel-deploy-e058df83-df0f-4da3-a4ba-dd31e383be66.ps1 `
          -resourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} `
          -workspaceName ${{ secrets.WORKSPACE_NAME }} `
          -workspaceId ${{ secrets.WORKSPACE_ID }} `
          -directory ${{ secrets.DIRECTORY }} `
          -contentTypes ${{ secrets.CONTENT_TYPES }} `
          -sourceControlId ${{ secrets.SOURCE_CONTROL_ID }} `
          -rootDirectory ${{ secrets.ROOT_DIRECTORY }} `
          -githubAuthToken ${{ secrets.GH_AUTH_TOKEN }} `
          -githubRepository ${{ secrets.GH_REPOSITORY }} `
          -branchName ${{ secrets.BRANCH_NAME }} `
          -smartDeployment ${{ secrets.SMART_DEPLOYMENT }}
